name: UI Automation Pipeline
on:
  push:
    branches: [ branch-1 ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run UI Tests
        run: pytest --html=report.html --self-contained-html